### ISSUE TITLE
Exception while executing vad_test.py.

### ISSUE THREAD

**Issue by krishnamohan191** [jtkim-kaist/VAD#15]
Traceback (most recent call last):
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/lib/pycharm-community/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/kbarakam/Desktop/VAD/VAD/lib/python/VAD_test.py", line 62, in <module>
    pred, label = graph_test.do_test(graph_list[-1], data_dir, norm_dir, data_len, is_default, mode)
  File "/home/kbarakam/Desktop/VAD/VAD/lib/python/graph_test.py", line 89, in do_test
    valid_inputs, valid_labels = valid_data_set.next_batch(valid_batch_size)
  File "/home/kbarakam/Desktop/VAD/VAD/lib/python/data_reader_bDNN_v2.py", line 94, in next_batch
    self._input_spec_list[self._num_file]), batch_size, self._w)
IndexError: list index out of range

---> There is no txt file in input_dir, so when 0th index was accessed, Exception occured.
self._input_spec_list = sorted(glob.glob(input_dir+'/*.txt'))

    def next_batch(self, batch_size):
        if self._start_idx == self._w:
            self._inputs = self._padding(
                self._read_input(self._input_file_list[self._num_file],
                                 self._input_spec_list[self._num_file]), batch_size, self._w)

1) Can you upload the text file in input_dir?
2) Also, can you give more info regarding data_len = int(arg) which is passed as a parameter to graph_test.do_test()?
3) Do you have comparison results of this VAD algorithm with webrtc VAD? If so, can you post it here

**Comment by jtkim-kaist** [comment]
I'm very sorry for late answer.

1. audio_dir = './data/example/clean_speech.wav' # directory for specific audio file

2. the length of your audio data i.e. length(audio) in matlab notation.

3. Unfortunately there is no comparison.

**Comment by jiashihuigithub** [comment]
i met the same issue with you, i haven't the *.txt file, please tell me how to solve it?
