### ISSUE TITLE
Error while running main.py file

### ISSUE THREAD

**Issue by rajeevbaalwan** [jtkim-kaist/VAD#18]
Traceback (most recent call last):
  File "./lib/python/VAD_test.py", line 60, in <module>
    pred, label = graph_test.do_test(graph_list[-1], data_dir, norm_dir, data_len, is_default, mode)
  File "/home/rajeev/pb/VAD/lib/python/graph_test.py", line 89, in do_test
    valid_inputs, valid_labels = valid_data_set.next_batch(valid_batch_size)
  File "/home/rajeev/pb/VAD/lib/python/data_reader_bDNN_v2.py", line 144, in next_batch
    inputs = utils.bdnn_transform(inputs, self._w, self._u)
AttributeError: module 'lib.matlab_py.utils' has no attribute 'bdnn_transform'

utils file does not contain any function with name bdnn_transform

**Comment by jtkim-kaist** [comment]
It seems you import incorrect utils.py, utils.py definitely has bdnn_transform.

**Comment by rajeevbaalwan** [comment]
Sorry!! There were 2 utils file. I choosed the wrong one.
When u are removing matlab dependency for MRCG  Extraction and other TODO's. ????????

**Comment by jtkim-kaist** [comment]
We already remove the dependency : ). From py branch you can enjoy full python version.

**Comment by rajeevbaalwan** [comment]
Okay !! :+1:  
Does py branch support spectogram feature instead of MRCG ???

**Comment by jtkim-kaist** [comment]
No while I have the spectrogram feature based feature based VAD but not arranged yet for uploading. I will upload that version in this month. thank you!

**Comment by rajeevbaalwan** [comment]
Thanks!! Eagerly waiting for that.
